import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import { Poppins } from "next/font/google";
import NavBar from "./Components/NavBar";

const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Theme>
          <NavBar />
          <main>{children}</main>
        </Theme>
      </body>
    </html>
  );
}
